"""2025 E MaixCAM 视觉参数。现场调参优先修改本文件。"""

FRAME_WIDTH = 240
FRAME_HEIGHT = 180
PROCESS_EVERY_N_FRAMES = 2
MAX_CONTOURS_TO_CHECK = 12

GAUSSIAN_KERNEL = (3, 3)
MORPH_KERNEL_SIZE = 3
USE_MORPH_CLOSE = False
BORDER_SIZE = 0
CANNY_LOW = 50
CANNY_HIGH = 150
APPROX_EPSILON = 0.025
MIN_AREA_RATIO = 0.02
MAX_AREA_RATIO = 0.95
MIN_ASPECT_RATIO = 1.00
MAX_ASPECT_RATIO = 2.20
TARGET_ASPECT_RATIO = 297.0 / 210.0
MAX_ANGLE_COSINE = 0.42
MIN_RECTANGULARITY = 0.55

AIM_REFERENCE_X = FRAME_WIDTH // 2
AIM_REFERENCE_Y = FRAME_HEIGHT // 2

TRACK_EMA_ALPHA = 0.35
HOLD_FRAMES = 2
LOST_FRAMES = 5
LOG_INTERVAL_S = 0.5

UART_ENABLED = False
UART_DEVICE = "/dev/ttyS1"
UART_BAUDRATE = 115200
UART_TX_PIN = "A19"
UART_RX_PIN = "A18"

PROTOCOL_VERSION = 1
PACKET_TYPE_TARGET = 1
